config/routes.rb
Einkarem::Application.routes.draw do

  resources :students  do
    resources :tracks
    resources :requests
  end

  get "managment/index"

  post "managment/createHospital"
  post "managment/updateHospital"
  post "managment/createDepartment"

  put "managment/update/(:obj)/(:id)"  => 'managment#update', as: 'managment_update'
  put "track/change/(:student)/(:task)"  => 'track#change', as: 'track_change'
  put "track/update/(:obj)/(:id)"  => 'track#update', as: 'track_update'
  put "students/updateRequest/(:id)"  => 'students#updateRequest', as: 'student_updateRequest'
  get "managment/destroy"
  get "students/deleteFile/(:id)/(:type)" => 'students#deleteFile', as: 'student_deleteFile'

  post "track/changeDorms"
  post "track/changePayment"
  post "track/changeLaundry"
  post "track/changeLibrary"
  post "track/changeLaundryBack"
  post "track/changeLibraryBack"

  get "log_out" => "sessions#destroy", :as => "log_out"
  post "" => "sessions#create", as: "log_in"
  resources :users

   root :to => 'sessions#new'

end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :arrival_date,
                  :birthday,
                  :country,
                  :languages,
                  :name,
                  :passport,
                  :past_departments,
                  :university,
                  :year,
                  :photo,
                  :study_approval,
                  :request_form,
                  :dorms_form,
                  :status,
                  :payment,
                  :requests_attributes,
                  :mail

  default_scope order: 'arrival_date'

  has_many :requests,  :dependent=>:destroy
  has_one :track,  :dependent=>:destroy
  accepts_nested_attributes_for :requests, :allow_destroy => true

  has_attached_file :photo,
                    :storage => :dropbox,
                    :styles => { :thumb => "180x180>" },
                    :dropbox_credentials => "#{Rails.root}/config/dropbox.yml",
                    :dropbox_options => {
                        :path => proc { "studex-einkarem/files/#{id}/photo_#{photo.original_filename}" },
                        :unique_filename => true
                    }
  has_attached_file :study_approval,
                    :storage => :dropbox,
                    :dropbox_credentials => "#{Rails.root}/config/dropbox.yml",
                    :dropbox_options => {
                        :path => proc { "studex-einkarem/files/#{id}/studyapproval_#{study_approval.original_filename}" },
                        :unique_filename => true
                    }
  has_attached_file :request_form,
                    :storage => :dropbox,
                    :dropbox_credentials => "#{Rails.root}/config/dropbox.yml",
                    :dropbox_options => {
                        :path => proc { "studex-einkarem/files/#{id}/requestform_#{request_form.original_filename}" },
                        :unique_filename => true
                    }
  has_attached_file :dorms_form,
                    :storage => :dropbox,
                    :dropbox_credentials => "#{Rails.root}/config/dropbox.yml",
                    :dropbox_options => {
                        :path => proc { "studex-einkarem/files/#{id}/dormsform_#{dorms_form.original_filename}" },
                        :unique_filename => true
                    }

  before_save :default_values

  def default_values
      self.status= 1 if !self.status # 1 == treatment
      self.payment= '0' if !self.payment

  end

  def self.search(search, countrySearch, statusSearch, requestSearch)
    unless search.blank?
      #find(:all, conditions: ['name LIKE ?', "%#{search}%"], :order => 'arrival_date')
      includes(:requests).where('requests.department' => search) | where{(name =~ "%#{search}%") | (mail =~ "%#{search}%") | (university =~ "%#{search}%")}
    else
      unless countrySearch.blank?
        #find(:all, :conditions => ['country = ?', "#{countrySearch}"], :order => 'arrival_date')
        where(country: countrySearch)
      else
        unless statusSearch.blank?
          #find(:all, :conditions => ['status LIKE ?', "#{statusSearch}"], :order => 'arrival_date')
          where(status: statusSearch)
        else
          unless requestSearch.blank?
            includes(:requests).where('requests.department' => requestSearch)
         else
          #find(:all, :conditions => ['status NOT LIKE ?', I18n.t('students.statuses.finished')], :order => 'arrival_date')
          where{{status.not_eq => 4}} # 4 == finished
            end
        end
      end
    end
  end
end

app/controllers/students_controller.rb
# coding: utf-8

class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  before_filter :checkDate, only: [:update, :create]

  def checkDate
    if params[:student] && params[:student][:birthday]
      params[:student][:birthday] = fixDate(params[:student][:birthday])
      params[:student][:arrival_date] = fixDate(params[:student][:arrival_date])
      params[:student][ :requests_attributes].values.each { |r|
        r[:begin_date] = fixDate(r[:begin_date])
        r[:finish_date] = fixDate(r[:finish_date])
      }
    end
  end

  def fixDate(date)
    if date.nil?
      return
    end

    day, month, year = date.split('/')

    if day.nil? or month.nil? or year.nil?
      date
      return
    end

    if year.length == 2
      year = (year.to_i < 40) ? '20'+year : '19'+year
    end

    date = day+'/'+month+'/'+year
    date
  end

  def deleteFile
    @student = Student.find(params[:id])
    type = params[:type]
    @student.update_attribute(type, nil)
    @student.save
    redirect_to @student
  end

  def index
    @students = Student.search(params[:search], params[:country_search], params[:status_search], params[:request_search])
    @active = "by_name" if   params[:search]
    @active = "by_country" if   params[:country_search]
    @active = "by_status" if params[:status_search]
    @active = "by_request" if params[:request_search]

    _load_constants

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    _load_constants

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new
    @title = "יצירת סטודנט חדש"
    @student.requests.build


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
    @title = " עריכת כרטיס סטודנט: #{@student.name} "
    (1-@student.requests.length).times do
      @student.requests.build
    end
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])
    @track = Track.new(params[:track])
    @student.track=@track
      respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
    def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_path }
      format.json { head :no_content }
    end
  end

  def updateRequest
    @request = Request.find(params[:id])
    if @request.update_attributes(params[:request])
      respond_with_bip(@request)
    else
      respond_with_bip(@request)
    end
  end

  private

  def _load_constants
    request_statuses = {
        pending: {
            id: 1,
            title: t('requests.statuses.pending')
        },
        treatment: {
            id: 2,
            title: t('requests.statuses.treatment')
        },
        approved: {
            id: 3,
            title: t('requests.statuses.approved')
        },
        declined: {
            id: 4,
            title: t('requests.statuses.declined')
        }
    }
    @request_statuses_array = request_statuses.values.map { |s| s.values }

    @student_statuses = {
        treatment: {
            id: 1,
            title: t('students.statuses.treatment')
        },
        confirmed: {
            id: 2,
            title: t('students.statuses.confirmed')
        },
        came: {
            id: 3,
            title: t('students.statuses.came')
        },
        finished: {
            id: 4,
            title: t('students.statuses.finished')
        }
    }
    #@student_statuses_array = @student_statuses.values.collect{|p| [p[:title],p[:id]]}
  end


end

app/helpers/students_helper.rb
module StudentsHelper
  def ldate(dt, hash = {})
    dt ? l(dt, hash) : nil
  end

  def printAge (student)
    if !student.birthday
      ""
    else
      now = Time.now.utc.to_date
      age = now.year - student.birthday.year - (student.birthday.to_date.change(:year => now.year) > now ? 1 : 0)
      "("+t("students.age")+": "+age.to_s+")"
    end
end


  def print_tasks(student)
    output = ''
    ['dorms','got_dorms', 'payment', 'laundry', 'library', 'laundry_back', 'library_back'].each do |t|
      output += print_task(student, t) unless (t == 'laundry_back' and !student.track['laundry']) or
          (t == 'library_back' and !student.track['library'])  or
          (t == 'got_dorms' and !student.track['dorms'])
    end
    output.html_safe
  end

  def print_task(student, task)
    if student.track[task]
      css_class = 'success'
      icon = 'icon-ok'
    else
      css_class = ''
      icon = 'icon-asterisk'
    end

    render partial: 'students/task', locals: {
        student: student,
        task: task,
        css_class: css_class,
        icon: icon
    }
  end

end

app/views/students/_form.html.erb
<div class="container f32">

  <div class="topbar">
    <%= link_to  '<i class="icon-remove"></i> '.html_safe+t('actions.cancel'), students_path, :class=>"floatleft"%>
    <h2><%= @title %></h2>
  </div>
  <div class="row">
    <div class="span10 offset1">
      <div class="well">
        <%= nested_form_for @student do |f| %>

            <legend><%= t("students.details") %></legend>
            <div class="row-fluid">
              <div class="span6">
                <p>
                  <label><%= t("students.full_name") %></label>
                  <%= f.text_field :name, tabindex: 1 %>
                </p>
                <p>
                  <label><%= t("students.birthday") %></label>
                <div class="input-append">
                  <%= f.text_field :birthday, tabindex: 3, class: 'datefield datefield_past', value: ldate(@student.birthday )  %>
                  <span class="add-on"><i class="icon-calendar"></i></span>
                </div>
                </p>
                <p>
                  <label><%= t("students.university") %></label>
                  <%= f.text_field :university, tabindex: 5 %>
                </p>
                <p>
                  <label><%= t("students.languages") %></label>
                  <%= f.text_field :languages, tabindex: 7 %>
                </p>
                <p>
                  <label><%= t("students.mail") %></label>
                  <%= f.text_field :mail, tabindex: 9 %>
                </p>
                <p>
                  <label><%= t("students.payment") %></label>
                  <%= f.text_field :payment, tabindex: 11 %>
                </p>
              </div>
              <div class="span6">
                <p>
                  <label><%= t("students.country") %></label>
                  <%= f.collection_select :country,  Country.order('name_heb ASC') ,  :id, :name_heb,{}, tabindex: 2 %>
                </p>
                <p>
                  <label><%= t("students.arrival_date") %></label>
                <div class="input-append">
                  <%= f.text_field :arrival_date, tabindex: 4, class: 'datefield', value: ldate(@student[:arrival_date]) %>
                  <span class="add-on"><i class="icon-calendar"></i></span>
                </div>
                </p>
                <p>
                  <label><%= t("students.year") %></label>
                  <%= select_tag("student[year]", options_for_select([['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5], ['6', 6]], @student.year), tabindex: 6)%>
                </p>
                <p>
                  <label><%= t("students.past_departments") %></label>
                  <%= f.text_field :past_departments, tabindex: 8, id: 'departments_tags' %>
                </p>
                <p>
                  <label><%= t("students.passport") %></label>
                  <%= f.text_field :passport, tabindex: 10 %>
                </p>
              </div>
            </div>

            <legend><%= t("requests.title") %></legend>

            <table class="table table-condensed">
              <thead>
              <tr>
                <th><%= t("requests.department") %></th>
                <th><%= t("requests.hospital") %></th>
                <th><%= t("requests.begin_date") %></th>
                <th><%= t("requests.finish_date") %></th>
              </tr>
              </thead>
            </table>
            <% i=12 %>
            <% @student.requests.order('begin_date').each do |request| %>
                <%= f.fields_for :requests, request, wrapper_tag: 'tr' do |request_form| %>
                    <%= request_form.collection_select :department,  RefDepartment.order('name ASC'),  :name, :name,{},{ :class => "input-medium", tabindex: i}%>
                    <%= request_form.collection_select :hospital,  RefHospital.order('name ASC'),  :name, :name,{},{ :class => "input-medium",tabindex: (i+1)} %>
                    <%= request_form.text_field :begin_date, :class => "datefield input-small", value: ldate(request.begin_date), :size => "16",tabindex: (i+2)  %>
                    <span class="add-on"><i class="icon-calendar"></i></span>
                    <%= request_form.text_field :finish_date, :class => "datefield input-small",value: ldate(request.finish_date), :size => "16",tabindex: (i+3)  %>
                    <span class="add-on"><i class="icon-calendar"></i></span>
                    <%= request_form.link_to_remove '<i class="icon-remove"></i>'.html_safe %>
                    <br>
                <% end %>
                    <% i=i+4 %>
            <% end %>
            <p><%= f.link_to_add t("requests.add"), :requests %></p>

            <legend><%= t("files.title") %></legend>
            <div class="row-fluid">
              <div class="span6">
                <p>
                  <label><b><%= t("files.photo") %></b></label>
                  <%= f.file_field :photo %>
                </p>
                <p>
                  <label><b><%= t("files.study_approval") %></b></label>
                  <%= f.file_field :study_approval %>
                </p>
              </div>
              <div class="span6">
                <p>
                  <label><b><%= t("files.request_form") %></b></label>
                  <%= f.file_field :request_form %>
                </p>
                <p>
                  <label><b><%= t("files.dorms_form") %></b></label>
                  <%= f.file_field :dorms_form %>
                </p>
              </div>
            </div>


            <legend></legend>
            <p style="text-align: center">
              <br/><span style="margin-left: 20px;">    <%= link_to  '<i class="icon-remove"></i> '.html_safe+t("actions.cancel"), students_path, :class=>"floatleft"%></span>
              <button type="submit" class="btn btn btn-success "><i class="icon-ok icon-white"></i><%= " "+t("actions.submit") %></button>
            </p>
        <% end %>
      </div>
    </div>
  </div>

  <hr>

</div> <!-- /container -->
</html>

app/views/students/_task.erb
<tr class=<%= css_class  %>>
  <td>
    <span><b><%= t("tasks.#{task}") %></b></span><br/>
    <a id="edit<%= task %>" href="#"><i class="icon-pencil"></i></a>
    <%= best_in_place student.track, task+'_c', path: track_update_path(obj: task+'_c', id: student.id) , activator: "#edit#{task}", html_attrs: { class: 'input-medium' }, nil: t("message.entercomment") %>
  </td>
  <td>
    <%= link_to(raw("<i class=\"#{icon}\"></i>"), track_change_path(student: student, task: task), :method => :put,  :class => "btn btn-small") %>

  </td>
</tr>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<%= stylesheet_link_tag 'vendor/flags32' %>
<div class="container f32">

  <div class="row">
    <div class="span3">
      <%= link_to t("index.create_student"), new_student_path, class: 'btn btn-large btn-primary span2 newstudent' %>

    </div>
    <div class="span9">
      <div class="control-group">
        <div class="controls">
          <div class="input-append">
            <%= form_tag students_path, :method => 'get' do %>
                <p>
                  <%= text_field_tag :search, params[:search], :class=>"span4 btn-large", :id=>"search", :placeholder=>t("index.search_by_name_university_mail_department") %>
                  <button type="submit" class="btn btn-large"><i class="icon-search"></i></button>
                </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="span3">
      <div class="tabbable tabs-left filterslables">
        <ul class="nav nav-tabs">
          <li class=<%= 'active' if @active == 'by_country' %>>
            <a><div class="li">
              <h4><%= t("index.search_by_country") %> </h4>
              <%= form_tag students_path, :method => 'get', :class => 'submit_on_change' do %>
                  <p>
                    <%= collection_select(:country_search, params[:country_search], Country.where(id: Student.pluck(:country)).order('name_heb ASC'), :id, :name_heb, options = { :include_blank => t("index.choose_country"), selected: params[:country_search]}, html_options = {:class => :span2, :id => 'country_search', :name => :country_search})  %>
                  </p>
              <% end %>
            </div></a>
          </li>
          <li class="<%= 'active' if @active == 'by_status' %>">
            <a><div class="li">
              <h4><%= t("index.search_by_status") %></h4>
              <%= form_tag students_path, :method => 'get', :class => 'submit_on_change' do %>
                  <p>
                    <%= select(:status_search, params[:status_search], @student_statuses.values.collect{|p| [p[:title],p[:id]]}, options = { selected: params[:status_search], :include_blank => t('index.choose_status')}, html_options = {:class => :span2, :id => 'status_search', :name => :status_search} ) %>

                  </p>
              <% end %>
            </div></a>
          </li>
          <li class=<%= 'active' if @active == 'by_request' %>>
            <a><div class="li">
              <h4><%= t("index.search_by_request") %> </h4>
              <%= form_tag students_path, :method => 'get', :class => 'submit_on_change' do %>
                  <p>
                    <%= collection_select(:request_search, params[:request_search], RefDepartment.all, :name, :name, options = { :include_blank => t("index.choose_department"), selected: params[:request_search]}, html_options = {:class => :span2, :id => 'request_search', :name => :request_search})  %>
                  </p>
              <% end %>
            </div></a>
          </li>
        </ul>
      </div>

    </div>
    <div class="span9">
      <table class="table table-hover table-condensed">
        <thead>
        <tr>
          <th><%= t("students.name") %></th>
          <th><%= t("students.arrival_date") %> </th>
          <th><%= t("students.country") %></th>
          <th><%= t("students.status") %></th>
        </tr>
        </thead>
        <tbody>
        <% if @students %>
            <% @students.each  do |s|%>
                <tr class="clickable" onclick="location.href='<%= student_path(s) %>'">
                  <td>
                    <%= link_to s.name, s %>
                    <br><span class="email"><%= s.mail%></span>
                  </td>
                  <td><%= ldate(s.arrival_date) %></td>
                  <% country = Country.find(s.country) %>
                  <% flagCode = "flag #{country.code}".downcase %>
                  <td><span class="country"><i class='<%=flagCode%>'></i> <%= country.name_heb %></span></td>
                  <td><%= @student_statuses.find{|k, v| v[:id] == s.status.to_i }.last[:title] %></td>
                </tr>
            <% end %>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <hr>
</div> <!-- /container -->

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<%= stylesheet_link_tag 'vendor/flags32' %>
<div class="container f32">

  <div class="topbar">
    <div class="btn-group floatleft">
      <%= link_to '<i class="icon-edit"></i> ערוך'.html_safe, edit_student_path(@student), class: 'btn' %>
      <%= link_to '<i class="icon-trash icon-white"></i> מחק'.html_safe, @student, :method => :delete, data: { confirm: t("students.delete_confirm") }, class: "btn btn-danger" %>

    </div>
    <% country = Country.find(@student.country) %>
    <% flagCode = "flag #{country.code}".downcase %>
    <h2><%= @student.name %> <span class="country">(<i class='<%=flagCode%>'></i> <%= country.name_heb %>)</span></h2>
  </div>
  <div class="row">
    <div class="span4">
      <div class="well">
        <span class="status"><%= t("students.status")%>:
          <%= best_in_place @student, :status, :type => :select, :collection => @student_statuses.values.collect{|p| [p[:id],p[:title]]},html_attrs: { class: 'input-small' }, :activator => "#editStatus" %>
        </span>
        <a id="editStatus" href="#">(<%= t("actions.update") %>)</a>
        <hr/>
        <h4><%= t("tasks.title") %> </h4>
        <table class="table">
          <%= print_tasks(@student) %>
        </table>
      </div>
    </div>
    <div class="span8">
      <div class="well">
        <% if @student.photo? %>
            <a href="<%= @student.photo.url %>"><%= image_tag @student.photo.url(:thumb), :class => 'passportimg' %></a>
           <span class="deletephoto"><%= link_to '<i class="icon-remove"></i> '.html_safe, student_deleteFile_path(student: @student, type: 'photo'), data: { confirm: t("students.delete_file_confirm") }, rel: "tooltip", title: t('delete_file') %></span>
      <% end %>
        <h3 class="nospace"><%= t("students.details") %> </h3>
        <ul>
          <li><b><%= t("students.passport") %>: </b> <%=@student.passport %></li>
          <li><b><%= t("students.birthday") %>: </b><%= ldate(@student.birthday) %> <%= printAge(@student)  %> </li>
          <li><b><%= t("students.mail") %>: </b><%= @student.mail %></li>
          <li><b><%= t("students.university") %>: </b> <%= @student.university %></li>
          <li><b><%= t("students.year") %>: </b> <%= @student.year %></li>
          <li><b><%= t("students.arrival_date") %>: </b><%= ldate(@student.arrival_date) %></li>
          <li><b><%= t("students.languages") %>: </b> <%= @student.languages %></li>
          <li><b><%= t("students.past_departments") %></b>: <%= @student.past_departments %></li>
        </ul>
        <div class="row-fluid centered">
          <% if @student.study_approval? %>
              <div class="span3"> <%= link_to '<i class="icon-file"></i> '.html_safe+t("files.study_approval"), @student.study_approval.url  %>
              <%= link_to '<i class="icon-remove"></i> '.html_safe, student_deleteFile_path(student: @student, type: 'study_approval'), data: { confirm: t("students.delete_file_confirm") }, rel: "tooltip", title: t('delete_file')  %></div>
          <% end %>
          <% if @student.request_form? %>
              <div class="span3"> <%= link_to '<i class="icon-file"></i> '.html_safe+t("files.request_form"), @student.request_form.url  %>
              <%= link_to '<i class="icon-remove"></i> '.html_safe, student_deleteFile_path(student: @student, type: 'request_form'), data: { confirm: t("students.delete_file_confirm") }, rel: "tooltip", title: t('delete_file')  %></div>
          <% end %>
          <% if @student.dorms_form? %>
              <div class="span3"> <%= link_to '<i class="icon-file"></i> '.html_safe+t("files.dorms_form"), @student.dorms_form.url  %>
              <%= link_to '<i class="icon-remove"></i> '.html_safe, student_deleteFile_path(student: @student, type: 'dorms_form'), data: { confirm: t("students.delete_file_confirm") }, rel: "tooltip", title: t('delete_file')  %></div>
          <% end %>
        </div>
      </div>
      <div class="well">
        <h3 class="nospace"><%= t("requests.title") %></h3>
        <table class="table table-condensed">
          <thead>
          <tr>
            <th><%= t("requests.department") %></th>
            <th><%= t("requests.hospital") %></th>
            <th><%= t("requests.begin_date") %></th>
            <th><%= t("requests.finish_date") %></th>
            <th><%= t("requests.status") %></th>
          </tr>
          </thead>
          <tbody>
          <% if @student.requests %>
              <% @student.requests.order('begin_date').each  do |r|%>
                  <tr>
                    <td><%= r.department %></td>
                    <td><%= r.hospital %></td>
                    <td><%= ldate(r.begin_date) %></td>
                    <td><%= ldate(r.finish_date) %></td>
                    <td>
                      <%= best_in_place r, :status,:path => student_updateRequest_path(r.id), :type => :select, :collection => @request_statuses_array ,html_attrs: { class: 'input-small' }, :activator => "#edit#{r.id}" %>
                      <a id="edit<%=r.id %>"  href="#">(<%= t("actions.update") %>)</a>
                    </td>
                  </tr>
              <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <hr>
</div> <!-- /container -->