config/routes.rb
Einkarem::Application.routes.draw do

  resources :students  do
    resources :tracks
    resources :requests
  end

  get "managment/index"

  post "managment/createHospital"
  post "managment/updateHospital"
  post "managment/createDepartment"

  put "managment/update/(:obj)/(:id)"  => 'managment#update', as: 'managment_update'
  put "track/change/(:student)/(:task)"  => 'track#change', as: 'track_change'
  put "track/update/(:obj)/(:id)"  => 'track#update', as: 'track_update'
  put "students/updateRequest/(:id)"  => 'students#updateRequest', as: 'student_updateRequest'
  get "managment/destroy"
  get "students/deleteFile/(:id)/(:type)" => 'students#deleteFile', as: 'student_deleteFile'

  post "track/changeDorms"
  post "track/changePayment"
  post "track/changeLaundry"
  post "track/changeLibrary"
  post "track/changeLaundryBack"
  post "track/changeLibraryBack"

  get "log_out" => "sessions#destroy", :as => "log_out"
  post "" => "sessions#create", as: "log_in"
  resources :users

   root :to => 'sessions#new'

end

app/models/managment.rb
class Managment < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/managment_controller.rb
class ManagmentController < ApplicationController
  def index
    @management = true
    @departments = RefDepartment.all
    @hospitals = RefHospital.all
    @newHospital = RefHospital.new
    @newDepartment = RefDepartment.new
  end

  #def create
  #  @obj = (params.respond_to? :ref_department) ?
  #      RefDepartment.new(params[:ref_department]) :
  #      RefHospital.new(params[:ref_hospital])
  #
  #  if @obj.save
  #    redirect_to managment_index_path
  #  else
  #    flash.now.alert = "Invalid name"
  #    render "index"
  #    #redirect_to action: 'index', notice: 'illegal name'
  #  end
  #end

  def createHospital
    @newHospital = RefHospital.new(params[:ref_hospital])
    if @newHospital.save
      redirect_to managment_index_path
    else
      #flash.now.alert = "Invalid name"
      redirect_to action: 'index'#, notice: 'illegal name'
    end
  end

  def createDepartment
    @newDepartment = RefDepartment.new(params[:ref_department])
    if @newDepartment.save
      redirect_to managment_index_path
    else
      #flash.now.alert = "Invalid name"
      redirect_to action: 'index'
    end
  end

  def update
      @obj = (params[:obj] == 'department') ?
          RefDepartment.find(params[:id]) :
          RefHospital.find(params[:id])

      if @obj.update_attributes(params["ref_#{params[:obj]}"])
        respond_with_bip(@obj)
      else
        respond_with_bip(@obj)
      end
end

  def destroy
  end
end

app/helpers/managment_helper.rb
module ManagmentHelper
end

app/views/managment/index.html.erb
<div class="container">

  <p id="notice"><%= params[:notice] %></p>
  <div class="row">
    <div class="span6">
      <div class="well">
        <h3><%= t("management.hospitals.title") %></h3>
        <span><%= t("management.hospitals.warning") %></span>
        <hr/>
        <table class="table">
          <thead>
          <tr>
            <th class="span4"><%= t("management.name") %></th>
          </tr>
          </thead>
          <tbody>
          <% if @hospitals %>
              <% @hospitals.each  do |d|%>
                  <tr>
                    <td><%= best_in_place d, :name, :path => managment_update_path(obj: 'hospital', id: d.id), :activator => "#editHospital#{d.id}" %></td>
                    <td><a id="<%= "editHospital#{d.id}" %>"  href="#"><%= t("actions.edit") %></a></td>
                  </tr>
              <% end %>
          <% end %>
          </tbody>
          <tfoot>
          <tr>
            <td colspan="2">
              <%= form_for(@newHospital, url: managment_createHospital_path, html: {class: 'form-inline'}) do |f| %>
                  <%= f.text_field :name %>
                  <%= f.submit t("actions.submit"), class: 'btn' %>
              <% end %>
            </td>
          </tr>
          </tfoot>
        </table>

      </div>
    </div>
    <div class="span6">
      <div class="well">
        <h3><%= t("management.departments.title") %></h3>
        <span><%= t("management.departments.warning") %></span>
        <hr/>
        <table class="table">
          <thead>
          <tr>
            <th><%= t("management.name") %></th>
          </tr>
          </thead>
          <tbody>
          <% if @departments %>
              <% @departments.each  do |d|%>
                  <tr>
                    <td><%= best_in_place d, :name, :path => managment_update_path(obj: 'department', id: d.id), :activator => "#editDepartment#{d.id}" %></td>
                    <td><a id="<%= "editDepartment#{d.id}" %>"  href="#"><%= t("actions.edit") %></a></td>
                  </tr>
              <% end %>
          <% end %>
          </tbody>
          <tfoot>
          <tr>
            <td colspan="2">
              <%= form_for(@newDepartment, url: managment_createDepartment_path, html: {class: 'form-inline'}) do |f| %>
                  <%= f.text_field :name %>
                  <%= f.submit t("actions.submit"), class: 'btn' %>
              <% end %>
            </td>
          </tr>
          </tfoot>
        </table>

      </div>
    </div>
  </div>

  <hr>

</div> <!-- /container -->