config/routes.rb
Einkarem::Application.routes.draw do

  resources :students  do
    resources :tracks
    resources :requests
  end

  get "managment/index"

  post "managment/createHospital"
  post "managment/updateHospital"
  post "managment/createDepartment"

  put "managment/update/(:obj)/(:id)"  => 'managment#update', as: 'managment_update'
  put "track/change/(:student)/(:task)"  => 'track#change', as: 'track_change'
  put "track/update/(:obj)/(:id)"  => 'track#update', as: 'track_update'
  put "students/updateRequest/(:id)"  => 'students#updateRequest', as: 'student_updateRequest'
  get "managment/destroy"
  get "students/deleteFile/(:id)/(:type)" => 'students#deleteFile', as: 'student_deleteFile'

  post "track/changeDorms"
  post "track/changePayment"
  post "track/changeLaundry"
  post "track/changeLibrary"
  post "track/changeLaundryBack"
  post "track/changeLibraryBack"

  get "log_out" => "sessions#destroy", :as => "log_out"
  post "" => "sessions#create", as: "log_in"
  resources :users

   root :to => 'sessions#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Einkarem</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">

  <%= stylesheet_link_tag   "headers", :media => "all" %>
  <%= csrf_meta_tags %>

  <%= javascript_include_tag 'vendor/modernizr-2.6.1-respond-1.1.0.min' %>
</head>

<body>

<% unless @hide_header %>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/students"><%= image_tag 'einkarem_logo.png' %><%= t("application.title") %></a>
          <div class="nav-collapse collapse">
            <div class="btn-group pull-right">
              <% if @management %>
                  <%= link_to '<i class="icon-home"></i> '.html_safe+t("application.home"), students_path, class: 'btn' %>
              <% else %>
                  <%= link_to '<i class="icon-wrench"></i> '.html_safe+t("application.management"), managment_index_path, class: 'btn' %>
              <% end %>
              <%= link_to '<i class="icon-share-alt"></i> '.html_safe+t("application.exit"), log_out_path, class: 'btn' %>
            </div>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
<% end %>

<%= yield %>

<footer class="container">
  <p class="span12">&copy; 2012 <%= t('copyright') %> / barakarg@gmail.com</p>
</footer>

<%= javascript_include_tag 'footers' %>

</body>
</html>